name: docsenv

channels:
      - conda-forge

dependencies:
      - python=3.7
      - numpy
      - conda-forge::sphinx-autodoc-typehints 
      - conda-forge::sphinx-gallery
      - conda-forge::sphinx-argparse
