name: docsenv

channels:
      - conda-forge

dependencies:
      - python=3.7
      - numpy
      - pip
      - scipy 
      - dask
      - cartopy=0.19.0.post1 
      - matplotlib=3.3.4
      - h5py
      - sphinx_rtd_theme
      - sphinx-autodoc-typehints 
      - sphinx-gallery
      - sphinx-argparse
